### ISSUE TITLE
Namespace Collisions With Standard Npgsql Driver

### ISSUE THREAD

**Issue by WalternativE** [pircher-software/npgsql-cratedb#3]
Hello!

We are currently trying to include CrateDB in one of our .NET solutions. The project which handles persistence abstractions already includes a top level set of APIs as well as a range of implementations of these abstract APIs for MS SQL Server, Oracle and PostgreSQL.

We tried to add an implementation for CrateDB using the npgsql based crate driver and encountered problems due to namespace collisions with the standard npgsql driver.

Do you see a way for us to work around this issue? We thought about removing our npgsql dependency and working of the npgsql classes in the crate fork but this would introduce quite a lot of unwanted additional coupling.

Thanks in advance for your response.

**Comment by apircher** [comment]
Hi WalternativE,

sorry, but the npgsql based crate driver is not intended to be used side by side with the original npgsql driver. Instead we are working to get the changes needed for CrateDB merged upstream into the original npgsql driver. So finally you should be able to just use the original npgsql driver to connect to CrateDB.

I would suggest that you currently just use the npgsql based crate driver to connect to PostgreSQL. The changes for CrateDB are activated by putting "Compatibility Mode=CrateDB" into the connection string. If the compatibility mode is not set to "CrateDB", the driver behaves exactly like the original npgsql.

Further Crate is working on a change that will allow npgsql to recognize CrateDB while connecting to it - which will remove the need to set a compatibility mode in the connection string. At that point you will be able to just use the original npgsql driver without doing anyting special to connect to CrateDB.

**Comment by WalternativE** [comment]
Thank you for the information. We will do as you specified :)
